// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadelStore.Data;

#nullable disable

namespace PadelStore.Data.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260406141251_SeedOneMoreProduct")]
    partial class SeedOneMoreProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PadelStore.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PadelStore.Data.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c5d88a-b33e-47f6-bbf2-a1605f77857b"),
                            BrandName = "Nike"
                        },
                        new
                        {
                            Id = new Guid("eb8608d9-3afc-4de5-b335-2635a1d3d584"),
                            BrandName = "Adidas"
                        },
                        new
                        {
                            Id = new Guid("6c041405-fc59-446d-abf6-9800acccc7fd"),
                            BrandName = "Bullpadel"
                        },
                        new
                        {
                            Id = new Guid("c3ea1eed-d829-4072-b0dd-1eb48694bbee"),
                            BrandName = "Wilson"
                        });
                });

            modelBuilder.Entity("PadelStore.Data.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6546657-e20f-400c-a541-084f9af110a7"),
                            CategoryName = "Rackets"
                        },
                        new
                        {
                            Id = new Guid("ba2f5f1c-a270-43a7-8d32-923a98ab7b3d"),
                            CategoryName = "Balls"
                        },
                        new
                        {
                            Id = new Guid("d8d7a869-833a-42dd-8573-8f2ce007de7c"),
                            CategoryName = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("c18232f3-981a-4f77-a51e-62d755dcdfb4"),
                            CategoryName = "Accesories"
                        });
                });

            modelBuilder.Entity("PadelStore.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PadelStore.Data.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f875dee-e80c-4076-bcc1-af7d6b33e5fc"),
                            BrandId = new Guid("6c041405-fc59-446d-abf6-9800acccc7fd"),
                            CategoryId = new Guid("b6546657-e20f-400c-a541-084f9af110a7"),
                            ImageUrl = "https://media.strefatenisa.com.pl/public/media/2b/69/e7/1721085111/vertex-03-23.png?ts=1745861188",
                            IsDeleted = false,
                            Price = 299m,
                            ProductDescription = "Bullpadel Vertex 03 23: несравнима сила и прецизност за напреднали играчи на падел",
                            ProductName = "Bullpadel Vertex 03"
                        },
                        new
                        {
                            Id = new Guid("6018ef62-c57c-4bfe-b0c8-ff7b276f2e11"),
                            BrandId = new Guid("c3ea1eed-d829-4072-b0dd-1eb48694bbee"),
                            CategoryId = new Guid("b6546657-e20f-400c-a541-084f9af110a7"),
                            ImageUrl = "https://media.strefatenisa.com.pl/public/media/78/78/f0/1742840687/wr166911d_0_blade_pro_v3_padel_green-png-high-res.jpg?ts=1745861582",
                            IsDeleted = false,
                            Price = 270m,
                            ProductDescription = "Отлично представяне във всяко действие на играта с тази универсална ракета Wilson, изработена от карбон, грапави повърхности и мека гума за взискателни играчи.",
                            ProductName = "Wilson Blade Pro"
                        },
                        new
                        {
                            Id = new Guid("056de4b2-c23d-4da8-a1a4-7248e6bb4fe2"),
                            BrandId = new Guid("eb8608d9-3afc-4de5-b335-2635a1d3d584"),
                            CategoryId = new Guid("b6546657-e20f-400c-a541-084f9af110a7"),
                            ImageUrl = "https://www.padelnuestro.com/media/catalog/product/1/1/113673-pala-adidas-adipower-carbon-ctrl-ar1ca3u381500x1500-1.jpg",
                            IsDeleted = false,
                            Price = 260m,
                            ProductDescription = "Стиковете Adidas Adipower Carbon CTRL 2025 предлагат превъзходен контрол, прецизност и съвременни технологии. Идеални са за напреднали играчи, търсещи пъргавина, мощност и издръжливост при всеки удар.",
                            ProductName = "Adidas Adipower CTRL"
                        },
                        new
                        {
                            Id = new Guid("12c1eb5d-5b6d-47bc-a549-ddd8e97da705"),
                            BrandId = new Guid("c3ea1eed-d829-4072-b0dd-1eb48694bbee"),
                            CategoryId = new Guid("ba2f5f1c-a270-43a7-8d32-923a98ab7b3d"),
                            ImageUrl = "https://padelmarket.com/cdn/shop/files/10301.jpg?v=1725951119",
                            IsDeleted = false,
                            Price = 10m,
                            ProductDescription = "Топките за падел Wilson Premier Padel Speed ​​предлагат перфектната комбинация от производителност и издръжливост, за да ви помогнат да извлечете максимума от всяка игра.",
                            ProductName = "Wilson Padel Balls"
                        },
                        new
                        {
                            Id = new Guid("d5eebd00-c92e-491c-9457-967a5edd4c99"),
                            BrandId = new Guid("eb8608d9-3afc-4de5-b335-2635a1d3d584"),
                            CategoryId = new Guid("ba2f5f1c-a270-43a7-8d32-923a98ab7b3d"),
                            ImageUrl = "https://www.zonadepadel.com/14416-large_default/box-of-adidas-speed-rx-balls-24-x-3.jpg",
                            IsDeleted = false,
                            Price = 12m,
                            ProductDescription = "Вземете най-добрата цена за една от най-добрите топки за падел тенис, с цялото качество на Adidas, за да се насладите на най-доброто представяне.",
                            ProductName = "Adidas Speed RX Balls"
                        },
                        new
                        {
                            Id = new Guid("db59af0e-510b-423a-a7a6-5c4f3476e377"),
                            BrandId = new Guid("b2c5d88a-b33e-47f6-bbf2-a1605f77857b"),
                            CategoryId = new Guid("d8d7a869-833a-42dd-8573-8f2ce007de7c"),
                            ImageUrl = "https://media.strefatenisa.com.pl/public/media/cf/36/77/1721052350/nike-court-air-zoom-zero-white-black-volt-1.jpg?ts=1745860551",
                            IsDeleted = false,
                            Price = 120m,
                            ProductDescription = "NikeCourt Air Zoom Vapor Pro 2: Мъжки обувки за тенис на клей, проектирани за носене на кортове с клей и падел",
                            ProductName = "Nike Court Air Zoom"
                        },
                        new
                        {
                            Id = new Guid("131a6c67-aef4-429d-b4a2-c139109a293e"),
                            BrandId = new Guid("eb8608d9-3afc-4de5-b335-2635a1d3d584"),
                            CategoryId = new Guid("d8d7a869-833a-42dd-8573-8f2ce007de7c"),
                            ImageUrl = "https://s.shopsector.com/uploads/productgalleryfile/images/1200x1200/maratonki-adidas-gamecourt-2-ki0781-1.jpg",
                            IsDeleted = false,
                            Price = 100m,
                            ProductDescription = "Бъдете уверени във всеки мач, сет и среща. Леката мрежеста горна част и подплатената пета правят тези обувки adidas Gamecourt 2.0 перфектния ви партньор за тенис.",
                            ProductName = "Adidas GameCourt"
                        },
                        new
                        {
                            Id = new Guid("c74b3a3e-3b37-426b-b0e8-1ddf9890ff66"),
                            BrandId = new Guid("b2c5d88a-b33e-47f6-bbf2-a1605f77857b"),
                            CategoryId = new Guid("c18232f3-981a-4f77-a51e-62d755dcdfb4"),
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7q-JkNvxST3R6FGtcUxSMXAgP7TeCr-rPtg&s",
                            IsDeleted = false,
                            Price = 80m,
                            ProductDescription = "Специално спортен дизайн: Създаден за любители на тениса със специализирани отделения. Здрав материал: Изработен от висококачествен полиестер, издържащ на честа употреба. Оптимален размер: Перфектно балансирани размери за носене на всички необходими вещи без излишно натоварване.",
                            ProductName = "Padel Bag Nike"
                        },
                        new
                        {
                            Id = new Guid("7c42bf44-693f-48ab-8edc-ababf33ae739"),
                            BrandId = new Guid("eb8608d9-3afc-4de5-b335-2635a1d3d584"),
                            CategoryId = new Guid("c18232f3-981a-4f77-a51e-62d755dcdfb4"),
                            ImageUrl = "https://cdncloudcart.com/34739/products/images/5519/padel-gripove-adidas-pack-3-white-6962342b9eb62_600x600.jpeg?1768043579",
                            IsDeleted = false,
                            Price = 15m,
                            ProductDescription = "Тези микроперфорирани оувъргрипове са създадени за играчи, които търсят максимален комфорт и сигурен захват дори при интензивна игра. Специалната им структура позволява ефективно абсорбиране на пот и влага, като поддържа ръката суха и стабилна през цялото време.",
                            ProductName = "Grip Pack Adidas"
                        },
                        new
                        {
                            Id = new Guid("ffedc79d-35d9-403d-a508-9aeae65222e6"),
                            BrandId = new Guid("6c041405-fc59-446d-abf6-9800acccc7fd"),
                            CategoryId = new Guid("b6546657-e20f-400c-a541-084f9af110a7"),
                            ImageUrl = "https://www.zonadepadel.com/16515-zdp_customer/bullpadel-hack-03-2024.jpg",
                            IsDeleted = false,
                            Price = 310m,
                            ProductDescription = "Запознайте се с Bullpadel Hack 03 23 - перфектният аксесоар за напреднали или агресивни играчи, които жадуват за превъзходна комбинация от силна сила на удара и оптимален контрол. Със своята уникална диамантена форма и баланс към главата тази ракета гарантира феноменална сила на удара.",
                            ProductName = "Bullpadel Hack 03"
                        },
                        new
                        {
                            Id = new Guid("7f8cfbae-4cc0-495c-b614-dcccff1b2848"),
                            BrandId = new Guid("c3ea1eed-d829-4072-b0dd-1eb48694bbee"),
                            CategoryId = new Guid("b6546657-e20f-400c-a541-084f9af110a7"),
                            ImageUrl = "https://media.strefatenisa.com.pl/public/media/88/40/fd/1721070394/wr112011u_0_pro_staff_v2_tour_bl_ye_rd-png-high-res.jpg?ts=1745861264",
                            IsDeleted = false,
                            Price = 280m,
                            ProductDescription = "Wilson Pro Staff V2 Tour Padel 2 не е обикновена ракета за гребане. Това е най-съвременна екипировка, специално разработена за напреднали играчи и професионалисти, които търсят максимален контрол на ударите си.",
                            ProductName = "Wilson Pro Staff"
                        },
                        new
                        {
                            Id = new Guid("bc632621-3a8b-4e23-8c41-3fb22c628c4b"),
                            BrandId = new Guid("b2c5d88a-b33e-47f6-bbf2-a1605f77857b"),
                            CategoryId = new Guid("c18232f3-981a-4f77-a51e-62d755dcdfb4"),
                            ImageUrl = "https://cdn.ozone.bg/media/catalog/product/cache/1/image/400x498/a4e40ebdc3e371adff845072e1c73f37/r/a/75cfb7c6c9cb85a76305e067171037ae/ranitsa-nike---academy-team--22-l--sinya-31.jpg",
                            IsDeleted = false,
                            Price = 70m,
                            ProductDescription = "Раница Academy Team 22 L има едно основно отделение с двупосочен цип. Голям външен джоб с цип, който може да побере топка. Вътрешен джоб, който може да побере лаптоп с размер на екрана до 15 инча.",
                            ProductName = "Nike Backpack"
                        },
                        new
                        {
                            Id = new Guid("481d1039-e133-4c2f-9c65-832ffff1866a"),
                            BrandId = new Guid("eb8608d9-3afc-4de5-b335-2635a1d3d584"),
                            CategoryId = new Guid("c18232f3-981a-4f77-a51e-62d755dcdfb4"),
                            ImageUrl = "https://cdn.sportdepot.bg/files/catalog/detail/IC3568_01.jpg",
                            IsDeleted = false,
                            Price = 10m,
                            ProductDescription = "Бъдете фокусирани върху играта си, точка след точка. Тези големи тенис накитници от adidas ви помагат да отвеждате влагата и да поддържате концентрацията си. Меки, еластични и абсорбиращи, те ще гарантират, че ще държите окото си върху топката до гейма, сета и мача.",
                            ProductName = "Adidas Wristband"
                        });
                });

            modelBuilder.Entity("PadelStore.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PadelStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PadelStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PadelStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PadelStore.Data.Models.CartItem", b =>
                {
                    b.HasOne("PadelStore.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelStore.Data.Models.ApplicationUser", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Order", b =>
                {
                    b.HasOne("PadelStore.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PadelStore.Data.Models.OrderItem", b =>
                {
                    b.HasOne("PadelStore.Data.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelStore.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Product", b =>
                {
                    b.HasOne("PadelStore.Data.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelStore.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Review", b =>
                {
                    b.HasOne("PadelStore.Data.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelStore.Data.Models.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PadelStore.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PadelStore.Data.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
